### ISSUE TITLE
HLISA.errors.HLISAException: The element could not be moved to. This is likely an error in HLISA,                please raise an issue if it happens

### ISSUE THREAD

**Issue by k3fjeee** [droefs/HLISA#22]
Traceback (most recent call last):
  File "C:\Users\xyz\Desktop\coinmarket\cm.py", line 72, in <module>
    actions.move_to_element(slider).perform()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\HLISA\hlisa_action_chains.py", line 101, in perform
    action()
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\HLISA\hlisa_action_chains.py", line 83, in <lambda>
    self.chain.append(lambda: actions.move_to_element(element, addDelayAfter))
  File "C:\Users\xyz\AppData\Local\Programs\Python\Python39\lib\site-packages\HLISA\selenium_actions.py", line 80, in move_to_element
    raise HLISAException(error_msg)
HLISA.errors.HLISAException: The element could not be moved to. This is likely an error in HLISA,                please raise an issue if it happens

this error does not occur if I use selenium

`slider = wait.until(EC.element_to_be_clickable((By.CLASS_NAME, 'css-1w5k7wg')))
    time.sleep(1.2)
    actions.move_to_element(slider).pause(0.001).click_and_hold().move_by_offset(pix, 0).pause(0.001).move_by_offset(pix, 0).pause(0.01).move_by_offset(pix, 0).pause(0.001).move_by_offset(pix, 0).pause(0.001).release().perform()`

**Comment by bkrumnow** [comment]
Hey, 
thanks for opening this issue. We would like to investigate the issue further. Could you provide us with the site's URL?
Also, the selector used for slider and the value for _pix_ could help.

Side note: I don't think you need timeouts, as HLISA has timeouts integrated. The timeouts are non-static and simulate human behaviour. So, your code could be reduced to:

```python
actions.move_to_element(slider)
.click_and_hold()
.move_by_offset(pix, 0)
.release()
.perform()
```
